# Generated by Django 4.0.3 on 2022-03-24 22:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='img1',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='apps/'),
            preserve_default=False,
        ),
    ]
